pipeline {
    agent {
        node {
            label 'master'
            
        }
    }
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
	    
	stage ("Deploy - Tomcat") {
		steps {
			deploy adapters: [tomcat9(credentialsId: 'tomcat_creds', path: '', url: 'http://localhost:8085/')], contextPath: 'target/simple-java-maven-app', war: '**/*.war'
		}
		
	}
        stage ("Dynamic Analysis - DAST with OWASP ZAP") {
		steps {
			sh "docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:8085/target/simple-java-maven-app"
		}
	}
       
    }
}
